name 'olyn_litespeed'
maintainer 'Scott Richardson'
maintainer_email 'dev@grogwood.com'
chef_version '~> 16'
license 'GPL-3.0'
supports 'debian', '>= 10'
source_url 'https://gitlab.com/olyn/olyn_litespeed'
description 'Installs and configures Openlitespeed locally on the server'
version '1.0.3'

provides 'olyn_litespeed::default'
provides 'olyn_litespeed::common'
provides 'olyn_litespeed::litespeed'
provides 'olyn_litespeed::php'
provides 'olyn_litespeed::vhosts'
recipe 'olyn_litespeed::default', 'Installs and configures Openlitespeed locally on the server'
recipe 'olyn_litespeed::common', 'Shared blocks for the litespeed cookbook'
recipe 'olyn_litespeed::litespeed', 'Installs and configures the openlitespeed server'
recipe 'olyn_litespeed::php', 'Installs and configures the PHP for openlitespeed'
recipe 'olyn_litespeed::vhosts', 'Configures vhosts in openlitespeed'
